GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNIEpvaG4iLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNjU0NjA0NDczLCJleHAiOjE2NTQ2MDQ0ODh9.QdB1ucuo6XaRsBDYsT4G_vZc-taHOn4ovwHCRroiLdc

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "M John2",
    "email": "john@gmail.com",
    "password": "123456",
    "confPassword": "123455"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "123456"   
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/tickets

###
POST http://localhost:5000/tickets
Content-Type: application/json

{
    "kota_asal": "Aceh",
    "waktu_berangkat": "2022-06-09 10:00:00",
    "kota_tujuan": "Padang",
    "waktu_tiba": "2022-06-09 15:00:00",
    "nama_kereta":"PARAHYANGAN",
    "harga": "90000"
}

# Test Capstone
# ### Register
# POST http://ec2-34-212-169-254.us-west-2.compute.amazonaws.com/restapi/register
# Content-Type: application/json

# {
#     "email": "john@gmail.com",
#     "fullName": "John2",
#     "password": "123456",
#     "roles": [
#         "user"
#     ]
# }

# ###Login
# POST http://ec2-34-212-169-254.us-west-2.compute.amazonaws.com/restapi/login
# Content-Type: application/json

# {
#     "email": "john@gmail.com",
#     "password": "123456"
# }



